### ISSUE TITLE
Rozjeżdżanie się numerów linii (diff)

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#10]
![](https://lh3.googleusercontent.com/-2M_ud0aqRNg/VEauA8OubwI/AAAAAAAACxM/ZXXMF2wYGac/w480-h800/2014-10-21.jpg)

**Comment by liscju** [comment]
Pod linkiem download znajduje się nowa wersja do pobrania "Download Poprawione Issue #10" , jak mógłbyś to sprawdź i skomentuj.

**Comment by fracz** [comment]
jest ok
