### ISSUE TITLE
[S] Nie działa filtrowanie zmian

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#14]
Zarówno filtry ALL jak i NEW dają ten sam wynik.
Pozostałe filtry zawsze są puste (nie ma żadnych zmian).

**Comment by fracz** [comment]
Wmergowałem jedną zmianę na naszym Gerricie - aplikacja powinna wyświetlić coś w "merged" a jest pusto.

**Comment by liscju** [comment]
Zostało to poprawione, od wersji 0.3.4 powinno działać ok, jak będziesz miał czas to sprawdź i wrzuć komentarz.

**Comment by fracz** [comment]
Działa :-)

**Comment by fracz** [comment]
Jeszcze jakby domyslnie było ustawione na NEW byłoby super - w ALL trochę długo się to ładuje.

**Comment by liscju** [comment]
Poprawione, od wersji 0.3.6 domyślnie jest ustawione na NEW
