### ISSUE TITLE
[M] Poprawki do listy zmian

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#16]
![](http://home.agh.edu.pl/~fracz/mcr/2014_10_22_00.24.28.png)
1. Lista jest dziwnie wyrównana - niektóre zmiany są do lewej, inne do prawej.
2. Usunąłbym przycisk details i możliwość rozwijania zmian - nie widze w tym sensu. Informacje które są dostępne po rozwinięciu są dostępne w details. Usuwając przycisk i strzałkę byłoby więcej miejsca na komentarz oraz można by dodać flagi (fajki i krzyżyki tak jak w Gerricie albo zaznaczać status zmiany kolorem tła - do uzgodnienia); zmiana wtedy oczywiście otwierałaby się przez tapnięcie

**Comment by d00d171** [comment]
Ad 1: Mógłbyś zamieścić print screena tego ekranu po wcześniejszym włączeniu opcji "Pokaż granice układu" w ustawieniach telefonu w opcjach programisty? 
Nie wiem z czego wynika taki dziwny układ a u siebie nie udało mi się tego odtworzyć. 
Zdarzyło ci się coś takiego jeszcze gdzieś indziej? Jeżeli tak to czy dzieje się to dla jakiejś konkretnej zmiany, czy może dla któregoś z kolei elementu na tej liście?

Ad 2: Zastanowimy się nad tym.

**Comment by fracz** [comment]
Wydaje się że problem z rozjeżdzającymi się nazwami się rozwiązał :)

**Comment by d00d171** [comment]
Ad 2: Co byś powiedział na kolorowanie zmiany na liście w zależności od oceny dla labelki "Code Review" (czerwony/zielony/brak koloru), bez zmiany obecnego layoutu? Innych labelek bym tu nie umieszczał, bo może ich być sporo.

Podejrzenie podstawowego info na tej liście bez konieczności przechodzenia do ekranu szczegółów wydaje się użyteczne więc to bym zostawił. 

A co do komentarza to można dopasować wysokość elementu na liście do zawartości i będzie widoczny cały + zmniejszyć czcionkę do takiej jak jest w tych rozwiniętych szczegółach + zamiast buttona z napisem "Details" zrobić button z ikoną ( i ).
Wtedy dodatkowo z rozwiniętych szczegółów zniknął by "Subject".

Co ty na to?

**Comment by fracz** [comment]
Labelek zazwyczaj nie ma dużo. 2 max 3. Spróbowałbym wyświetlić wszystkie wartości na liście bo są ważne. Może nie robiłbym kolumn na każdą flagę z osobna tak jak jest w WEB UI, ale dodałbym po prawej kolumnę, w której by były skrótowe nazwy flag z wartościami i kolorami: (CR+1, V-1, CR-1). Jeśli flaga nie jest przyznana, nic sie nie wyświetla. Wartości dodatnie na zielono, ujemne na czerwono.

Podejrzenie "podstawowego info" zmiany nadal dla mnie nie ma sensu. Po pierwsze wymusza to konieczność przycisków (a najprościej jest po prostu tapać cały wiesz ze zmianą). Po drugie są to te same info co w details zmiany. W końcu po trzecie - jedyne co mnie interesuje przy wyborze zmiany z listy to czego ona dotyczy oraz jakie ma flagi (patrz wyżej). Nic więcej mi nie potrzeba. A jak potrzeba to znaczy że chcę zrobić z nią coś więcej - czyli ją otwieram.

Widoczność całego komentarza nie jest konieczna. Ważne że widać początek (zazwyczaj tam jest tag projektu). Dwie linie per zmiana jest jak najbardziej OK i nic bym tu nie zmieniał.

**Comment by d00d171** [comment]
Od wersji 3.29:
- jest możliwość przełączania się między widokiem Changes Explorera. Domyślnie jest prezentowana wersja na screenie poniżej a po przełączeniu (w menu u góry jest opcja Switch view) przechodzimy do widoku starego, w którym w rozwijalnych szczegółach też zostały dodane labelki. Wyszukiwanie i filtrowanie zmian pozostaje po przełączeniu.
- etykiety labelek widoczne w nagłówku listy to duże litery w ich nazwach
- na liście są wyświetlane minimalne wartości dla każdej labelki (wydaje mi się że tak samo działa na Gerricie)
- wartość labelki ma czerwone/zielone tło jeżeli jest minimalna/maksymalna, szare jeżeli nie można jej dodać dla danej zmiany (nie ma ikon bo byłby większy problem z określeniem szerokości dla różnych urządzeń i byłby rozjazd między nagłówkiem a wartościami)
- wartość labelki jest zielona/czerwona w zależności od tego czy jest +/-. Jeżeli jest to wartość min/maks nie kolorujemy tekstu, a tylko tło
- jeżeli byłoby więcej labelek niż się mieści na ekranie to jest horizontal scroll na labelkach(w tej chwili proporcje tekst/labelki to 7:2)
- na mniejszym ekranie mogą być łamane nazwy labelek w nagłówku listy, ale wydaje mi się że nie jest to większy problem a szkoda żeby zajmowały jeszcze więcej miejsca

![screenshot_2014-12-14-19-09-23](https://cloud.githubusercontent.com/assets/4409240/5428531/9130402c-83c7-11e4-86c5-474622238141.png)

**Comment by d00d171** [comment]
Jeżeli wygląda to jakbym się uparł przy pozostawieniu starego ekranu to trochę tak jest ;) A przy okazji nie chciałem usuwać funkcjonalności która już jest, skoro oba ekrany różni tylko sposób prezentacji tych samych danych, pobieranych tylko raz.

**Comment by fracz** [comment]
Jest OK, widać teraz wszystko. U mnie na telefonie w ogóle nie wyświetliła się labelka dla "CR" a w tej kolumnie gdzie powinna być obok zmian widać było tylko szare albo zielone paski (nie ma -1 ani +1). Ale może zostać.

Nie zakładam, że ktoś ma więcej niż 3 typy flag :-)

**Comment by d00d171** [comment]
HorizontallScroll nie działa na tych labelkach? Dodawałem żeby było więcej i dało się przewijać.

**Comment by fracz** [comment]
Działa, ale dziwnie. Tak wygląda domyślnie:

![](http://home.agh.edu.pl/~fracz/mcr/2014_12_14_21.06.18.png)

A tak jak przescrolluję w lewo:

![](http://home.agh.edu.pl/~fracz/mcr/2014_12_14_21.06.37.png)

Ale możecie to zostawić, nie jest to jakieś super istotne, widać o co chodzi. W tym pierwszym widoku ewentualnie przesunąłbym informacje o flagach z samego dołu na samą górę po rozwinięciu.

**Comment by fracz** [comment]
Zauważyłem też, że pojawił się niepotrzebny padding.

**Comment by d00d171** [comment]
Paddingi trochę zmieniłem i przerzuciłem labelki na początek. 
A z widocznością tych flag na nowym ekranie powalczymy przy okazji refactoringu layoutów do kolejnego releasu, może już na Androida 5 ;)
