### ISSUE TITLE
[M] Dziwne wyświetlanie flag przy komentowaniu zmiany

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#17]
![](http://home.agh.edu.pl/~fracz/mcr/2014_10_22_00.35.46.png)

Nie zawsze. Ale np zawsze przy wyświetlaniu zmiany "Fix error when printing board" z naszego Gerrita.

Dodałem tam customową flagę "MasterApproved" i myślałem że dlatego, ale druga zmiana z tego projektu działa ok.

Nie da się tego okienka zamknąć przez przycisk "Wstecz" w telefonie - trzeba klikać cancel.

**Comment by d00d171** [comment]
W tej chwili wyświetlanie jest poprawne jeżeli użytkownik jest dodany jako "Reviewer" do zmiany - do poprawy.

A zachowanie z zamykaniem tylko po naciśnięciu Cancel akurat bym zostawił, ale to już kwestia usability. Wolałbyś żeby back też zamykał okienko?

**Comment by fracz** [comment]
Wszędzie da się wsteczem z wszystkiego wyjść więc pomimo że jest przycisk cancel - wstecza bym nie blokował.

**Comment by d00d171** [comment]
Wstecz zamyka te popupy od wersji 0.3.17

**Comment by d00d171** [comment]
Poprawione od wersji v0.3.18
