### ISSUE TITLE
Poprawki ekranu konfiguracji

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#2]
Witam!
Na pierwszy ogień - ekran konfiguracji.
1. nie wiadomo, że podając hasło chodzi o HTTP Credentials - trzeba to wyraźnie zaznaczyć, że połączenie nie jest po SSH
2. po wpisaniu adresu URL bez http:// mówi, że jest niepoprawny; mogłoby być to tam wpisane od razu albo samo się uzupełniać
3. po dodaniu konfiguracji przycisk na dole staje sie niewidoczny ![niewidoczny przycisk](http://home.agh.edu.pl/~fracz/mcr/2014_10_21_12.26.14.png)

**Comment by liscju** [comment]
Witam,
Jeżeli chodzi o punkt pierwszy to wstawiłem labelke nad loginem/haslem uzytkownika ,punkt drugi poprawiłem - obecnie jeżeli użytkownik nie wpiszę na początku http:// uzupełnia się to automatycznie. Jeżeli chodzi o punkt trzeci to nie mam w tym momencie dostępu do telefonu z androidem( testuje to na tablecie) ale podejrzewam ,że wystarczy przewinąć w dół ekran aby ją zobaczyć, oczywiście jeżeli byłoby to wygodniejsze to można wstawić przycisk apply na górny action bar i wtedy byłby cały czas widoczny - byłbym wdzięczny za komentarz co do tego.
 Na wiki znajduje się link "Download Poprawione Issue #2" z poprawioną apką , jak znajdziesz chwilę to zobacz i napisz komentarz. No i dzięki za uwagi

**Comment by fracz** [comment]
Odnośnie 3 - nie da się przesunąć ekranu a w zupełności by to wystarczyło. Pewnie trzeba to umieścić w ScrollView.

**Comment by liscju** [comment]
Prawdopodobnie masz rację , zmieniłem to i u mnie jest oki, uaktualnilem linka Download z issue 2 do najnowszej apki i czekam na komentarz czy obecnie jest ok.
