### ISSUE TITLE
[S] Wyświetlić numer zmiany w szczegółach

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#20]
Numer zmiany (ten cyfrowy, nie ChangeId) jest bardzo ważny przy developmencie - pobieramy kod za jego pomocą. Mozna wyświetlić go w szczegółach nawet na tym niebieskim pasku na górze obok "Change Info"

**Comment by d00d171** [comment]
Numer dodany w zakładce ChangeInfo jako pierwsza pozycja szczegółów. Myślę że na jedno wychodzi a przynajmniej będzie wiadomo co to za numerek. 

Od wersji 0.3.17
