### ISSUE TITLE
[M] Poprawić wyświetlanie dat w szczegółach zmiany

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#21]
Obecnie mam coś takiego:

Uploaded:
2014-10-14 10:30.47.0000000000

**Comment by d00d171** [comment]
Rozumiem że chciałbyś żeby nie były widoczne milisekundy; czy chodzi o jeszcze jakiś inny format?

//Dotyczy wyświetlania dat w całej aplikacji

**Comment by fracz** [comment]
Wystarczy taki format jak jest - bez milisekund.

**Comment by d00d171** [comment]
Poprawione wraz z Issue #25, od wersji v0.3.13
