### ISSUE TITLE
[M] Ukryć ikonę "About" jak jest niepotrzebna

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#23]
![](http://home.agh.edu.pl/~fracz/mcr/2014_10_22_00.47.06.png)

Często zabiera miejsce a nie jest to aż tak interesujące w trakcie review ;) Jak nie chcecie jej wyrzucić z tych ekranów zupełnie, przynajmniej ustawcie showAsAction="ifRoom" :-)

**Comment by liscju** [comment]
Jeżeli chodzi o tą ikonkę nie jesteśmy szczególnie uparci :P ta ikonka ma jedyne zastosowanie żeby w przyszłości jak liczba wersji będzie większa niż obecnie użytkownik mógł sprawdzić wersję appki w której występuje bug/ ewentualnie improvement. Moglibyśmy spokojnie ustalić żeby ta ikonka była tylko na ekranie Konfiguracji, bądź Przeglądarki zmian(Changes Explorer) - co ty na to?

**Comment by fracz** [comment]
Super - zostawmy w takim razie tą ikonkę tylko w tych dwóch miejscach.

**Comment by liscju** [comment]
Poprawione od wersji v0.3.7 , about jest tylko w okienku konfiguracji i wyszukiwarki zmian
