### ISSUE TITLE
[M] Wyświetlanie komentarzy

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#25]
![](http://home.agh.edu.pl/~fracz/mcr/2014_10_22_00.51.51.png)
- Domyślnie są ucięte (na dole)
- Przydałby się jakiś padding
- data

**Comment by d00d171** [comment]
Poprawka w v0.3.13
Ad1, Ad2. U mnie nie ucina, ale myślę że tak czy siak dodanie paddingu powinno to naprawić.
Ad3. Daty w całym systemie są teraz wyświetlane w takim formacie "yyyy-MM-dd HH:mm". Gdybyś wolał inny, albo któraś została w starym formacie to daj znać.

**Comment by fracz** [comment]
Chciałbym sprawdzić ale nie mogę zobaczyć komentarzy, które dodałem do tej zmiany: http://apps.iisg.agh.edu.pl:8081/#/c/22/1 - nie wyświetlają się.
