### ISSUE TITLE
[M] Możliwość ukrycia numerów linii

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#27]
Strasznie dużo miejsca na ekranie zajmują numery linii, a bardzo rzadko w sumie są one potrzebne. Powinno dać się ukryć / pokazać numery linii jakimś przyciskiem (domyślnie ukryte).

Podobnie - można zaoszczędzić miejsce poprzez pokazywanie lini z komentarzami kolorem podświetlenia zamiast ikonką ( i ). Wtedy na całym ekranie będzie tylko kod - to co jest najważniejsze.

**Comment by liscju** [comment]
Poprawione , od wersji 0.3.5( na wiki link )  domyślnie linie są ukryte, na action barze pojawił się przycisk do ukrywania/pokazywania linii , miałem wątpliwości jaką ikonkę powinien mieć ten przycisk więc proszę o komentarz czy działa i czy ikonka tego przycisku jest ok. Jeżeli chodzi o ikonkę (i) to proponuje żebyś zobaczył jak to teraz się prezentuje, jeżeli w dalszym ciągu zajmuje to za dużo miejsca w porównaniu do linii kodu to proponuje założyć oddzielne issue na to i zajmę się tym.

**Comment by fracz** [comment]
Ikonkami będziemy się zajmować potem :-)
