### ISSUE TITLE
[M] Zablokować możliwość oceniania zmian w stanie MERGED i ABANDONED

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#28]
Obecnie przy próbie oceny leci wyjątek - wysłałem stacktrace.

BTW - docierają te maile z dumpami do was?

**Comment by liscju** [comment]
Zrobione od wersji 0.3.8, przy próbie dodania komentarza  jako użytkownik anonymous ,lub gdy status zmiany to merged lub abondoned wyświetla komunikat na ekranie o braku możliwości dodania komentarza

**Comment by d00d171** [comment]
Maile docierają

**Comment by fracz** [comment]
Przy próbie dodania komentarza do linii faktycznie wyświetla się toast. Natomiast gwiazdką nadal mogę dodać komentarz (może zostać) oraz ocenić zmianę - wtedy nic się nie dzieje. Można by ukryć tam flagi albo przynajmniej pokazać "Unauthorized" tak jak jest to wyświetlane gdy nie mamy uprawnień.

**Comment by liscju** [comment]
Poprawione od wersji 0.3.19
