### ISSUE TITLE
[M] Zmiana sposobu zaznaczania linii zawierającej komentarze

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#29]
Na telefonie nadal zajmuje to 1/10 ekranu. Tym bardziej, że na początku nie ma żadnych komentarzy i jest zabrane miejsce w sumie nie wiadomo na co. Nadal jestem za podświetlaniem linii na wyraźny kolor - może żółty? Jako że zielone, czerwone i niebieskie mamy już zajęte.

**Comment by liscju** [comment]
Oczywiście tak możemy to zrobić - w jaki sposób proponowałbyś aby użytkownik mógł zobaczyć komentarze do linii np przycisk na action bar?

**Comment by fracz** [comment]
Jak przeglądam plik w celu odebrania review, mogę założyć że główną czynnością którą chcę wykonać jest przeczytanie komentarzy. Dlatego można je wyświetlić od razu po tapnięciu (zaznaczeniu) linii.

**Comment by liscju** [comment]
Zmienione od 0.3.24, linie są kolorowane na żółto ponadto jest robiony underline tych linii ,aby w diffie dla linii dodanych/odjętych czyli już pokolorowanych było widoczne ,że jest w nich komentarz , gdyż od tej wersji można oglądać komentarze tapnięciem zarówno z poziomu zwykłego kodu źródłowego jak i diffa.

**Comment by fracz** [comment]
Jest jeszcze niepotrzeny margines.

![](http://home.agh.edu.pl/~fracz/mcr/2014_10_31_16.08.45.png)

**Comment by liscju** [comment]
Margines usunięty od wersji 3.34
