### ISSUE TITLE
Nie można wyświetlić zmian (nic się nie dzieje)

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#3]
Po ustaleniu konfiguracji jak w Issue #2 przechodzę do następnego ekranu na którym nic się nie dzieje (czkeałem 2min):
![nic sie nie dzieje](http://home.agh.edu.pl/~fracz/mcr/2014_10_21_12.26.40.png)

Gerrit tam jest bliźniaczy do tego, który jest uruchomiony na porcie 8081. Są na nim zmiany (dużo).

Przy wpisaniu złego hasła HTTP otrzymuję Toast, że jest niepoprawne, więc autentykacja przebiega w porządku.

**Comment by liscju** [comment]
Czy ekran Changes Explorera jest za każdym razem pusty gdy konfiguracja jest ustawiona na korzystaniego z tego serwera czy też było to jednorazowe zachowanie?  Dodatkowo ,czy próbowałeś łączyć się z tym na porcie 8081 i jezeli tak to czy ekran też był pusty czy jest to zachowanie tylko dla tego serwera z duza iloscia zmian? Czy połączenie było po http,czy po https gdyż w tym momencie obsługiwane są tylko połączenia poprzez http.

**Comment by fracz** [comment]
Stworzyłem na gerricie 8081 projekt, który nie jest dostępny publicznie. Zmiany są widoczne dopiero po zalogowaniu (zmieniłem uprawnienia Read do refs/*). W aplikacji nawet po podaniu credentials zmiany nie sią widoczne.

**Comment by d00d171** [comment]
Poprawka wrzucona na wiki. Do weryfikacji.

**Comment by fracz** [comment]
Działa!
