### ISSUE TITLE
[S] Podświetlenie (zaznaczenie) zmienionej linii nie działa

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#30]
Jak na ekranie diff jest jakaś zmiana (np linia jest zielona) - po jej dotknięciu jej kolor nie zmienia się na niebieski, a powinien bo dzięki temu wiem, że do niej dodam komentarz.

**Comment by liscju** [comment]
Od wersji 0.3.14 znajduje się nowa wersja, dodałem troche przeźroczystości do linii z diffem żeby było widać podkreślenie - daj znać czy obecny wygląd jest ok.
