### ISSUE TITLE
[M] Nie można opublikować komentarzy

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#31]
Po wprowadzeniu komentarzy i opublikowania ich (klikam gwiazdkę i ok) aplikacja crashuje. Stacktrace wysłany.

**Comment by fracz** [comment]
Teraz zobaczyłem, że komentarze się publikują ale aplikacja crashuje.

**Comment by d00d171** [comment]
Ocenianie zmiany poprawione w wersji 0.3.10
Co do dodawania komentarze do pliku to są one w tej chwili publikowane od razu, a nie w momencie dodawania review dla całej zmiany. Jeżeli chciałbyś zmienić to zachowanie to prosiłbym o dodanie nowego issue.
