### ISSUE TITLE
[M] Obsługa dodawania i publikowania komentarzy w taki sposób jak na Gerricie

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#33]
Na Gerricie (Web) review wygląda tak: dodaję komentarze (drafty) i w tym czasie mogę je usuwać i edytować. Dopiero po ich opublikowaniu (i ewentualnej ocenie - funkcjonalność gwiazdki) są one widoczne. Chcielbyśmy żeby ten proces wyglądał tak samo w aplikacji.

Nie jestem pewny czy to nie jest to samo zadanie co #32

**Comment by d00d171** [comment]
Wrzuciłem wersję ze zmienioną obsługą dodawania komentarzy (od v.0.3.28).
Teraz można je edytować w widoku pliku i przed opublikowaniem review.

Są one obsługiwane w taki sam sposób jak w aplikacji webowej, tzn. zapisywane jako drafty do momentu opublikowania review.

Dodatkowo linie w pliku w których są "oczekujące" komentarze są oznaczone kolorem cyan i pogrubione. Nie miałem lepszego pomysłu ;) W podobny sposób oznaczone są pliki na liście ModifiedFiles, do których są jakieś komentarze (kolor cyan).
Daj znać co o tym myślisz/co chciałbyś zmienić.

**Comment by d00d171** [comment]
I przy okazji dodałem coś takiego że jak aplikacja padnie to przy kolejnym uruchomieniu nie korzystamy z ostatnio używanej konfiguracji, tylko pokazuje się ekran konfiguracji.

**Comment by fracz** [comment]
Jest super :)

**Comment by fracz** [comment]
W sumie nie. Dlaczego po dodaniu komentarza wracam na początek pliku? Powinienem zostać w tym miejscu gdzie byłem bo inaczej nie wiadomo co się dzieje.

**Comment by d00d171** [comment]
Poprawione.
