### ISSUE TITLE
[M] Wyświetlanie złych plików w zmianie

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#39]
Przykład: http://apps.iisg.agh.edu.pl:8081/#/c/22/
Na Gerricie zmienionych jest kilka plików, natomiast w aplikacji wyświetlają się dwa i w dodatku takie, których na Gerricie nie ma.

**Comment by fracz** [comment]
Edit: w aplikacji wyświetlają sie pliki ale z innej zmiany: http://apps.iisg.agh.edu.pl:8081/#/c/23/1

**Comment by fracz** [comment]
Po restarcie aplikacji działa, spróbuję znaleźć ścieżkę do odtworzenia problemu.

**Comment by fracz** [comment]
Teraz dzieje się to za każdym razem jak otwieram zmianę "Add SuperComplicatedCode" - wyświetlone tam pilki nie pochodzą z tej zmiany.

**Comment by d00d171** [comment]
Poprawione od wersji 0.3.17
