### ISSUE TITLE
[C] Dodać przycisk "Odśwież"

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#41]
Zarówno na liście zmian jak i w szczegółach - powinna być mozliwość ponownego pobrania danych z serwera.

**Comment by liscju** [comment]
Zrobione od wersji v0.3.25, przycisku odśwież nie ma tylko w okienku configuration i kodu źródłowego bo chyba zresztą nie miałby tam większego sensu.
