### ISSUE TITLE
[M] Ukryć niepotrzebne przyciski jak jest zbyt mało miejsca

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#46]
![](http://home.agh.edu.pl/~fracz/mcr/2014_10_31_16.05.11.png)

Przycisk "About" zasłania menu, przez co nie da się go wybrać. Ustawcie `android:showAsAction="ifRoom"` dla niekoniecznych przycisków.

BTW - co robi przycisk ze strzałką (drugi od lewej)?

**Comment by d00d171** [comment]
Poprawka pod wersji v0.3.28
