### ISSUE TITLE
[M] Brak możliwości dodawania komentarzy przy przełączaniu metody autentykacji

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#5]
Próbowałem dwuklik (dwutap), long tap itp - nic nie działa. Na screenie w podręczniku jest gwiazdka - nie ma u mnie takiego przycisku.

**Comment by d00d171** [comment]
Byłeś zalogowany? Gwiazdka pojawia się tylko kiedy na ekranie konfiguracji podasz HTTP Credentials

**Comment by fracz** [comment]
Owszem - jestem zalogowany.

**Comment by d00d171** [comment]
Jeśli chodzi o komentarz do całej zmiany to gwiazdka powinna być widoczna na ekranie ze szczegółami zmiany (Change Details) dla zalogowanego użytkownika. 
Żeby skomentować linijkę w kodzie źródłowym trzeba zrobić longclicka na wybranej linii.

Mógłbyś jeszcze raz się upewnić że obie te funkcjonalności nie działąją?
Czy zmieniałeś w międzyczasie login/hasło/urla na pierwszym ekranie?

**Comment by fracz** [comment]
Tak - zmieniałem (w sensie w aplikacji z anonymous na authenticated). Po zmianie na authenticated i restarcie aplikacji zaczęło działać.

**Comment by d00d171** [comment]
Błąd już nie występuje kiedy się przełączasz?

**Comment by fracz** [comment]
Nie sprawdzałem :-)

**Comment by fracz** [comment]
Nadal nie działa. Kroki:
1. Świeża instalacja aplikacji
2. Wprowadzenie danych repo bez użytkownika
3. Pokazanie listy zmian
4. Powrót do konfiguracji repo -> podanie użytkownika & apply
5. Zmiany wyświetlają się, ale po wejściu do nich nie ma przycisku "gwiazdka"

PS. Nie musicie wgrywać za każym razem zbudowanej apki - mogę sobie pullować kod i budować ją u siebie - ./gradlew installDebug przechodzi bez problemu. Rozumiem, że pracujecie na branchu dev?

**Comment by d00d171** [comment]
Tak, działamy na devie. Dla nas byłoby to znacznie wygodniejsze rozwiązanie gdybyś mógł to u siebie budować. Jeżeli nie stanowiłoby to problemu to moglibyśmy tak ustalić.
Zbudowaną apkę na wiki będziemy ewentualnie wrzucać po jakichś większych zmianach / co jakiś czas / przy kolejnym releasie.
Co ty na to ?

**Comment by fracz** [comment]
Dla mnie to żaden problem. Zauważyłem tylko, że na ./gradlew build nie wszystkie testy przechodzą :-)

**Comment by d00d171** [comment]
To jest zamierzone zachowanie.

**Comment by d00d171** [comment]
Poprawione w wersji 0.3.10
