### ISSUE TITLE
[M] Podwójne otwarcie listy komentarzy

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#6]
Jak szybko dotknę ikonki (i) w widoku pliku to lista komentarzy otwiera się dwa razy, szczególnie gdy komentarzy jest dużo. Odkryłem przy okazji próbowania dwukliku w #5

**Comment by d00d171** [comment]
Poprawione w v0.3.12.

**Comment by fracz** [comment]
W związku z #39 nie jestem w stanie sprawdzić.
