### ISSUE TITLE
[S] Zapamiętywanie ostatnio używanego Gerrita

### ISSUE THREAD

**Issue by fracz** [mobilecodereviewer/MobileCodeReviewer#8]
I automatyczne jego włączanie przy starcie aplikacji.

**Comment by d00d171** [comment]
Od wersji v0.3.15 ostatnio używana konfiguracja jest zapamiętywana i przy kolejnych uruchomieniach startujemy z nią.
Żeby zmienić konfigurację którą używamy, na ekranie Changes Explorera do menu została dodana akcja "Change configuration" która powoduje przejście do ekranu konfiguracji.
